breakpoints fix and sprites add
theater-theme/theater-theme pull request #5
Opened 2020-08-11 21:53 UTC by felipprodrigues

2020-08-14 13:12 UTC, matheusagcosta requested changes
@felipprodrigues Remember to add the `.DS_Store` file to the gitignore

2020-08-14 13:14 UTC, matheusagcosta requested changes

2020-08-14 13:14 UTC, matheusagcosta commented on _src/css/_contact.scss
> +    font-size: 48px;
@felipprodrigues just missing a tab

2020-08-14 13:14 UTC, matheusagcosta commented on _src/sprites/defs.svg
> +      <path d='M.184 10.462c-.779 4.906 1.401 10.823 8.123 13.006.12.022.231.032.335.032.782 0 1.32-.582 1.32-1.3-.097-.523.383-2.642-.92-2.357-2.519.536-2.821-.871-3.205-1.607 1.086 1.394 2.718 1.35
@felipprodrigues you don't need the `</path>`, instead you can auto close them like this `<path />`

2020-08-17 15:46 UTC, felipprodrigues commented
Last changes on portfolio_fix not commited

2020-08-17 19:10 UTC, matheusagcosta requested changes

2020-08-17 19:10 UTC, matheusagcosta commented on _src/css/_container.scss
> +  svg {
@felipprodrigues let's use a class instead

2020-08-17 19:10 UTC, matheusagcosta commented on _src/css/_container.scss
> +svg:not(:root) {
@felipprodrigues It would be nice to move this rule to a general scss file

2020-08-21 20:28 UTC, closed without merging